# Advance OOPS

In [3]:
class shape:
    def area(self,a):
        return 3.14*a*a
    def area(self,a,b):
        return a*b
s=shape()
print(s.area(3,4))
print(s.area(2))

12


TypeError: area() missing 1 required positional argument: 'b'

In [8]:
class Add:
    def result(self,a,b):
        print("Addition:",a+b)
class Multi(Add):
    def result(self,a,b):
        super().result(10,20)
        print("multiplication:",a*b)
a=Multi()
a.result(10,20)
m=Add()
m.result(10,20)

Addition: 30
multiplication: 200
Addition: 30


In [13]:
class A:
    def first(self):
        print("First function of class A")
    def second(self):
        print("Second function of class A")
class B(A):
    def first(self):
        print("First function of class B")
    def display(self):
        print("Display function of child class")
obj1=A()
obj2=B()
obj1.first()
obj2.first()
obj1.second()
obj2.second()
obj2.display()
obj1.display()


First function of class A
First function of class B
Second function of class A
Second function of class A
Display function of child class


AttributeError: 'A' object has no attribute 'display'

In [17]:
class A:
    def __init__(self,x):
        self.x=x
    def __add__(self,other):
        return self.x+other.x
class B:
    def __init__(self,x):
        self.x=x
a=A(100)
b=B(200)
print(a+b)

300


In [21]:
class A:
    def __init__(self,x):
        self.x=x
    def __add__(self,other):
        return self.x+other.x
obj1=A(1)
obj2=A(2)
obj3=A("Hello")
obj4=A("Hi")
print(obj1+obj2) #or print(A.__add__(obj1,obj2)) or print(obj1.__add__(obj2))
print(obj3+obj4) #or print(A.__add__(obj3,obj4)) or print(obj3.__add__(obj4))

3
HelloHi
3
HelloHi


In [3]:
class A:
    def __init__(self,x):
        self.x=x
    def __gt__(self,other):
        if self.x>other.x:
            return True
        else:
            return False
obj1=A(2)
obj2=A(3)

if obj1>obj2:
    print("obj1 is greater than obj2")
else:
    print("obj2 is greater than obj1")

obj2 is greater than obj1


**Mathematical operators**

In [ ]:
+ __add__(self,other)
- __sub__(self,other)
* __mul__(self,other)
/ __truediv__(self,other)
// __floordiv__(self,other)
%__mod__(self,other)
** __pow__(self,other)

**Comparison operators**

In [ ]:
< __lt__(self,other)
> __gt__(self,other)
<= __le__(self,other)
>= __ge__(self,other)
== __eq__(self,other)
!= __ne__(self,other)


In [10]:
class A:
    def __init__(self,x):
        self.x=x
    def __add__(self,other):
        return self.x+other.x
    def __sub__(self,other):
        return self.x-other.x
    def __mul__(self,other):
        return self.x*other.x
    def __truediv__(self,other):
        return self.x/other.x
    def __floordiv__(self,other):
        return self.x//other.x
    def __mod__(self,other):
        return self.x%other.x
    def __pow__(self,other):
        return self.x**other.x
    def __lt__(self,other):
        return self.x<other.x
    def __gt__(self,other):
        return self.x>other.x
    def __le__(self,other):
        return self.x<=other.x
    def __ge__(self,other):
        return self.x>=other.x
    def __eq__(self,other):
        return self.x==other.x
    def __ne__(self,other):
        return self.x!=other.x
obj1=A(1)
obj2=A(2)
print(obj1+obj2)
print(obj1-obj2)
print(obj1*obj2)
print(obj1/obj2)
print(obj1//obj2)
print(obj1%obj2)
print(obj1**obj2) 
print(obj1<obj2)
print(obj1>obj2)
print(obj1<=obj2)
print(obj1>=obj2)
print(obj1==obj2)
print(obj1!=obj2)

3
-1
2
0.5
0
1
1
True
False
True
False
False
True


In [12]:
class parent:
    def func1(self):
        print("Hello parent")
class child(parent):
    def func2(self):
        print("Hello child")
test=child()
test.func1()
test.func2()

Hello parent
Hello child


In [5]:
class parent1:
    def func1(self):
        print("Hello parent1")

class parent2:
    def func2(self):
        print("Hello parent2")
class parent3:
    def func2(self):
        print("Hello parent3")
class child(parent1,parent3,parent2):
    def func3(self):
        print("Hello child")
test=child()
test.func1()
test.func2()
test.func3()
print(child.__mro__)

Hello parent1
Hello parent3
Hello child
(<class '__main__.child'>, <class '__main__.parent1'>, <class '__main__.parent3'>, <class '__main__.parent2'>, <class 'object'>)


In [1]:
class grandparent:
    def func1(self):
        print("Hello grandparent")
class parent(grandparent):
    def func2(self):
        print("Hello parent")
class child(parent):
    def func3(self):
        print("Hello child")
test=child()
test.func1()
test.func2()
test.func3()
print(child.__mro__)

Hello grandparent
Hello parent
Hello child
(<class '__main__.child'>, <class '__main__.parent'>, <class '__main__.grandparent'>, <class 'object'>)


In [5]:
#hyrarchical inheritance
class parent:
    def func1(self):
        print("Hello parent")
class child1(parent):
    def func2(self):
        print("Hello child1")
class child2(parent):
    def func3(self):
        print("Hello child2")
obj1=child1()
obj2=child2()
obj1.func1()
obj1.func2()
obj2.func1()
obj2.func3()
print(child1.__mro__)
print(child2.__mro__)

Hello parent
Hello child1
Hello parent
Hello child2
(<class '__main__.child1'>, <class '__main__.parent'>, <class 'object'>)
(<class '__main__.child2'>, <class '__main__.parent'>, <class 'object'>)


In [10]:
#hybrid inheritance
class parent1:
    def func1(self):
        print("Hello parent1")
class parent2:
    def func2(self):
        print("Hello parent2")
class child1(parent1):
    def func3(self):
        print("Hello child1")
class child2(child1,parent2):
    def func4(self):
        print("Hello child2")
test1=child1()
test2=child2()
test1.func1()
test1.func3()
test2.func1()
test2.func2()
test2.func3()
test2.func4()
print(child1.__mro__)
print(child2.__mro__) 
print(child1.mro()) #list

Hello parent1
Hello child1
Hello parent1
Hello parent2
Hello child1
Hello child2
(<class '__main__.child1'>, <class '__main__.parent1'>, <class 'object'>)
(<class '__main__.child2'>, <class '__main__.child1'>, <class '__main__.parent1'>, <class '__main__.parent2'>, <class 'object'>)
[<class '__main__.child1'>, <class '__main__.parent1'>, <class 'object'>]


In [17]:
#super()
class parent:
    def __init__(self):
        self.attr1=50
        self.attr2=65
class child(parent):
    def __init__(self): 
        parent.__init__(self) #or super().__init__()
        self.attr3=45
test=child()
print(test.attr1)

50


In [23]:
#issubclass()
#isinstance()
class parent:
    def func1(self):
        print("Hello parent")
class child(parent):
    def func2(self):
        print("Hello child")
print(issubclass(child,parent))
print(issubclass(parent,child))

A=child()
B=parent()
print(isinstance(A,child))
print(isinstance(A,parent))
print(isinstance(B,child))
print(isinstance(B,parent))


True
False
True
True
False
True


In [30]:
#MRO : method resolution order
class A:
    def rk(self):
        print("class A")
class B(A):
    def rk(self):
        print("class B")
class C(A):
    def rk(self):
        print("class C")
class D(B,C):
    pass
r=D()
r.rk()
print(D.__mro__)
print(C.__mro__)
print(B.__mro__)

class B
(<class '__main__.D'>, <class '__main__.B'>, <class '__main__.C'>, <class '__main__.A'>, <class 'object'>)
(<class '__main__.C'>, <class '__main__.A'>, <class 'object'>)
(<class '__main__.B'>, <class '__main__.A'>, <class 'object'>)


In [5]:
class p1:
    def foo(self):
        print("foo from p1")
class p2:
    def foo(self):
        print("foo from p2")
    def bar(self):
        print("bar from p2")
class c1(p1,p2):
    pass
class c2(p2):
    def bar(self):
        print("bar from c2")
class GC(c1,c2):
    pass
gc=GC()
gc.bar()
gc.foo()
GC.mro()

bar from c2
foo from p1


[__main__.GC, __main__.c1, __main__.p1, __main__.c2, __main__.p2, object]

In [12]:
#Astract class
from abc import ABC,abstractmethod
class shape(ABC):
    def __init__(self,shape_name):
        self.shape_name=shape_name
    @abstractmethod
    def draw(self):
        pass
class circle(shape):
    def __init__(self):
        super().__init__("circle")
    def draw(self):
        print("draw circle")
c=circle()
c.draw()

draw circle


In [4]:
class Book:
    def __init__(self,no.ofauthor,publisher,ISBN,year):
        self.no.ofauthor=no.ofauthor
        self.authorname=[]
        self.publisher=publisher
        self.ISBN=ISBN
        self.year=year
        
    def display(self):
        print("NAME:",name)
        print("NO OF AUTHOR:",no.ofauthor)
        for i in range(self.no.ofauthor):
            a=input("Enter authorname:")
            print("AUTHOR NAME:",list[authorname])
        
        print("PUBLISHER:",publisher)
        print("ISBN:",ISBN)
        print("YEAR:",year)
        
class coursebook(Book):
    def __init__(self,coursename):
        super().__init__()
        self.coursename=coursename
    def display(self):
        super().display()
        print("COURSE NAME:",coursename)
b=book(2,"yashvi",7898,2025)
b.display()

SyntaxError: invalid syntax (<ipython-input-4-c9aa7eddac0b>, line 2)

In [6]:
class A:pass
class B:pass
class C:pass
class D:pass
class E:pass
class F:pass
class k1(C,A,B):pass
class k3(A,D,F):pass
class k2(B,D,E):pass
class z(k1,k3,k2):pass
print(z.mro())

[<class '__main__.z'>, <class '__main__.k1'>, <class '__main__.C'>, <class '__main__.k3'>, <class '__main__.A'>, <class '__main__.k2'>, <class '__main__.B'>, <class '__main__.D'>, <class '__main__.F'>, <class '__main__.E'>, <class 'object'>]


In [23]:
#the impliment following hirarkey create class staff take name and salary as its data members the derived class teaching as 
#subject it has data members an dthe derived no teaching has department has its data membner.
#the derived class override the method of base class.
class staff:
    def __init__(self,name,salary):
        self.name=name
        self.salary=salary
    def display(self):
        print("NAME:",self.name)
        print("SALARY:",self.salary)
        
class Teaching(staff):
    def __init__(self,name,salary,subject):
        super().__init__(name,salary)
        self.subject=subject
    def display(self):
        super().display()
        print("SUBJECT:",self.subject)
        
class Non_teaching(staff):
    def __init__(self,name,salary,dept):
        super().__init__(name,salary)
        self.dept=dept
    def display(self):
        super().display()
        print("SUBJECT:",self.dept)
t=Teaching("srushti",250000,"maths")
t.display()
print()
t1=Non_teaching("mahi",50000,"python")      
t1.display() 

NAME: srushti
SALARY: 250000
SUBJECT: maths

NAME: mahi
SALARY: 50000
SUBJECT: python


In [8]:
#create a class called student having name and email as its data members and constructor and put data as bound method 
#the init function should asign the values passed has parameters to the veriable the put data fun should display the data
#of the student create the another class phdguides having name and email as its data members you can use students as a veriable
#as a blank list.the stdents veriable is the list of student under the guide the phdguide class have 4 bound methods.init ,put
#data, add and remove.the init method initialize veriable put data should show the data guide including list of student the add
#method should have the student list of students of the guide and remove fun show remove the student if student exist in the 
#list of student.

class student:
    def __init__(self,name,email):
        self.name=name
        self.email=email
        
    def putdata(self):
        print("NAME:",self.name)
        print("EMAIL:",self.email)
        
class PHDguide(student):
    def __init__(self,name,email):
        super().__init__(name,email)
        self.student=[]
        
    def putdata(self):
        super().putdata()
        print("student:",self.student)
        
    def add(self):
        self.student.append(input("Add student:"))
        
    def remove(self):
        name=input("enter remove student:")
        if name in self.student:
            self.student.remove(name)
              
g1=PHDguide("sagar patel","sagar1770@gmail.com")
for i in range(3):
    g1.add()
g1.putdata()
g1.remove()
g1.putdata()

Add student:srushti
Add student:yashvi
Add student:kishu
NAME: sagar patel
EMAIL: sagar1770@gmail.com
student: ['srushti', 'yashvi', 'kishu']
enter remove student:kishu
NAME: sagar patel
EMAIL: sagar1770@gmail.com
student: ['srushti', 'yashvi']


In [ ]:
#create 3 class employee,perks and net salary when employee class as an abstract class employee class should have methods for
#following task
#1.to get employee details:employee id ,employee name and salary from user
#2.to print employee details
#3.to return salary
#4.an abstract method an emlopyee id
#perks class:
#1.calculate the DA,HRA,PF
#2.to print the indivitual and total perks
#net salary class:
#1.calculate total salary after perks
#2.print employee details with DA,HRA,PF,netsalary
#DA:35% HRA:17% PF:12%

In [5]:
from abc import ABC, abstractmethod
class Employee(ABC):
    def get_employee_details(self):
        self.employee_id = input("Enter employee ID: ")
        self.employee_name = input("Enter employee Name: ")
        self.salary = float(input("Enter salary: "))
    
    def print_employee_details(self):
        print(f"Employee ID: {self.employee_id}")
        print(f"Employee Name: {self.employee_name}")
        print(f"Salary: {self.salary}")
    
    def return_salary(self):
        return self.salary

    @abstractmethod
    def get_employee_id(self):
        pass

class Perks(Employee):
         
    def cal_perks(self):
        self.get_employee_details()
        salary=self.return_salary()
        self.da = 0.35 * salary  
        self.hra = 0.17 * salary  
        self.pf = 0.12 * salary 
        
    def print_perks(self):
        self.print_employee_details()
        print(f"DA: {self.da}")
        print(f"HRA: {self.hra}")
        print(f"PF: {self.pf}")
        
    def totalperks(self):
        t=self.da + self.hra - self.pf
        return t
    
    def get_employee_id(self):
        print("Emp_id")


class NetSalary(Perks):
    def gettotal(self):
        self.cal_perks()
        self.ns=self.return_salary()+self.totalperks()
        self.print_perks()
        print("Total salary:",self.ns)
empsalary=NetSalary()
empsalary.gettotal()

Enter employee ID: 1
Enter employee Name: mahi
Enter salary: 500
Employee ID: 1
Employee Name: mahi
Salary: 500.0
DA: 175.0
HRA: 85.0
PF: 60.0
Total salary: 700.0


In [2]:
class Bill:
    rates={"HDD":5000,"RAM":2000,"Printer":6000,"Pendrive":800}
    Items={"HDD":0,"RAM":0,"Printer":0,"Pendrive":0}
    for i,j in rates.items():
        print(i,j)
        accept=input("Want this item? Y/N: ").upper()
        if accept=="Y":
            Items[i]=int(input("Enter no of "+i+"'s:"))*rates[i]
        print()
    def __init__(self):
        print("1.cash payment\n2.cheque payment")
        payment_choice=int(input("Enter your choice:"))
        if payment_choice==1:
            cashpayment()
        elif payment_choice==2:
            cheque_no=int(input("Enter cheque no:"))
            bank=input("Enter Bank Name:")
            chequepayment(cheque_no,bank)
            
class cashpayment(Bill):
    def __init__(self):
        print()
        print("payment method is cash")
        sum=0
        for i,j in self.Items.items():
            sum+=j
        print("Amount to pay:",sum)
        dic={"2000 note":2000,"500 note":500,"200 note":200,"100 note":100,"50 note":50,"20 note":20,"10 note":10}
        print()
        for i,j in dic.items():
            if sum>=j:
                print(i+":",sum//j)
                sum=sum%j
class chequepayment(Bill):
    def __init__(self,cheque_no,bank):
        print("payment method is cheque")
        sum=0
        for i,j in self.Items.items():
            sum+=j
        print("Amount to pay:",sum)
        print("Cheque No.:",cheque_no)
        print("Bank Name:",bank)
b=Bill()

HDD 5000
Want this item? Y/N: y
Enter no of HDD's:1

RAM 2000
Want this item? Y/N: y
Enter no of RAM's:2

Printer 6000
Want this item? Y/N: y
Enter no of Printer's:1

Pendrive 800
Want this item? Y/N: y
Enter no of Pendrive's:1

1.cash payment
2.cheque payment
Enter your choice:2
Enter cheque no:23456
Enter Bank Name:BOI
payment method is cheque
Amount to pay: 15800
Cheque No.: 23456
Bank Name: BOI


In [ ]:
from abc import ABC, abstractmethod
class book(ABC):
    @abstractmethod
    def __init__(self):
        
    @abstractmethod
    def sell(self):
class fictionbooks(book):
    def __init__(self,title,author,quantity,price):
        self.title=title
        self.author=author
        self.quantity=quantity
        self.price=price
        
    def sell(self):
class Non_fictionbooks(book): 
    def __init__(self,title,author,quantity,price):
        self.title=title
        self.author=author
        self.quantity=quantity
        self.price=price
    def sell(self):
class cart:
    def __init__(self,id):
        self.id=id
    def add_to_cart(self,book):
        
    def displaycart(self):
        
    def bill(self):

In [2]:
# sort

import numpy as np
arr1 = np.array([1,4,53,6,7,])
print(np.sort(arr1))
arr2 = np.array([True,False,True])
print(np.sort(arr2))
arr3 = np.array([[3,4,2],[1,7,3],[4,2,5]])  #-1
print(np.sort(arr3,axis=0))
arr4 = np.array([[[3,2,8],[7,9,3]],[[6,7,2],[9,6,4]]])  #-1
print(np.sort(arr4))
print(np.sort(arr4,axis=0))
print(np.sort(arr4,axis=1))

[ 1  4  6  7 53]
[False  True  True]
[[1 2 2]
 [3 4 3]
 [4 7 5]]
[[[2 3 8]
  [3 7 9]]

 [[2 6 7]
  [4 6 9]]]
[[[3 2 2]
  [7 6 3]]

 [[6 7 8]
  [9 9 4]]]
[[[3 2 3]
  [7 9 8]]

 [[6 6 2]
  [9 7 4]]]
